[versions]
revanced-patcher = "21.0.0"
annotation = "1.9.1"
okhttp = "5.3.2"
# Tracking https://github.com/google/smali/issues/64.
#noinspection GradleDependency
smali = "3.0.5"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
android-library = { id = "com.android.library" }